### ISSUE TITLE
没找到留言的地方，请教一个问题

### ISSUE THREAD

**Issue by xiaoheike** [hailin0/elasticsearch-analysis-dynamic-synonym#1]
我有使用另外一个github项目，在使用过程中我遇到了问题，详细描述：
https://github.com/bells/elasticsearch-analysis-dynamic-synonym/issues/15
花了一周时间，还是没有找到该问题，请问你在使用过程中有遇到过吗？或者麻烦提供创建索引的设置以及查询的方法。

**Comment by hailin0** [comment]
在吗，加个qq交流一下这个问题

**Comment by hailin0** [comment]
@xiaoheike  568847614

**Comment by xiaoheike** [comment]
已经加你QQ啦
这个问题我已经解决啦，稍微有空我会将问题和解决的方法提交到github上。
